### ISSUE TITLE
cluster autoscaler tag cluster-autoscaler-1.32.0 does not container leader election flags

### ISSUE THREAD

**Issue by elmiko** [kubernetes/autoscaler#7903]
**Which component are you using?**:

/area cluster-autoscaler

**What version of the component are you using?**:

Component version: cluster-autoscaler-1.32.0 (from tag)

**What k8s version are you using (`kubectl version`)?**: n/a

**What environment is this in?**: terminal

**What did you expect to happen?**:

i expected to see the leader election options in the command line flags

**What happened instead?**:

i see the following:

(truncated)
```
      --kubeconfig string                                                  Path to kubeconfig file with authorization and master location information.
      --kubernetes string                                                  Kubernetes master location. Leave blank for default
      --lease-resource-name string                                         The lease resource to use in leader election. (default "cluster-autoscaler")
      --log-backtrace-at traceLocation                                     when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                                                     If non-empty, write log files in this directory (no effect when -logtostderr=true)
      --log-file string                                                    If non-empty, use this log file (no effect when -logtostderr=true)
      --log-file-max-size uint                                             Defines the maximum size a log file can grow to (no effect when -logtostderr=true). Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
```

**How to reproduce it (as minimally and precisely as possible)**:

1. `git checkout cluster-autoscaler-1.32.0`
2. `make build`
3. `./cluster-autoscaler-amd64 --help`
4. check help text

**Anything else we need to know?**:

building from the cluster-autoscaler-release-1.32 branch seems to work fine.

i think we need to create a 1.32.1 tag that works.

**Comment by Ronanc2797** [comment]
This error is also evident in the Helm chart version - cluster-autoscaler-chart-9.46.3.

Error: 
\unknown flag: --leader-elect
Usage of ./cluster-autoscaler:

I was under the impression that this was fixed in - https://github.com/kubernetes/autoscaler/issues/7668. In this issue the error seemed to be a result of kube_flag.InitFlags() being called before componentopts.BindLeaderElectionFlags(&leaderElection, pflag.CommandLine) in the cluster-autoscaler main.go file.

I can see this is resolved in cluster-autoscaler-chart-9.46.1, and these functions are called in the correct order (https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-chart-9.46.1/cluster-autoscaler/main.go#L703) yet the issue seems to persist?

**Comment by elmiko** [comment]
@Ronanc2797 to be clear, this is fixed on the master branch and the cluster-autoscaler-release-1.32 branch. i think we need to make a new tag for cluster-autoscaler-1.32.1.

**Comment by Ronanc2797** [comment]
@elmiko you are correct. I was looking at the updated helm chart branch which sources from master which is why I thought the changes were implemented. This still uses cluster-autoscaler-1.32.0 which explains why the error was still present. A new tag for 1.32.1 should fix things

**Comment by adrianb-ppb** [comment]
I see the last version of helm chart is still using version: 1.32.0 which has this bug, can you bump the helm chart version to use version 1.32.1 ?

**Comment by elmiko** [comment]
we do have a 1.32.1 tag now and the patch for the helm charts is posted. i think we should keep this issue open until the helm chart has merged.

/remove-lifecycle stale
